Algoritmo "Atividade_5"
// Disciplina  : Algoritmo e Lógica de Programação
// Professor   : André Olímpio 
// Autor(a)    : Isabella Oliveira Assis
// Data atual  : 15/09/2026
Var
vetorA: vetor [1..15] de inteiro
x : inteiro
Inicio

para x de 1 ate 15 faca
     escreva("Digite o ", x, "º numero:")
     leia(vetorA[x])

fimpara

para x de 2 ate 15 passo 2 faca
     escreva(vetorA[x], " ")
fimpara

Fimalgoritmo