Algoritmo "atividade_2"
// Disciplina  : Algoritmo e Lógica de Programação
// Professor   : André Olímpio 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Isabella Oliveira Assis
// Data atual  : 11/08/2026
Var

num1: inteiro
num2: inteiro
resp1: inteiro
resp2: inteiro
resp3: inteiro
resp4: real

Inicio

escreva("|Digite o primeiro número:")
leia(num1)
escreva("|Digite o segundo número:")
leia(num2)

resp1 <- num1 + num2
escreval("|Resultado Soma:", resp1)
resp2 <- num1 - num2
escreval("|Resultado Substração:", resp2)
resp3 <- num1 * num2
escreval("|Resultado Multiplicação:", resp3)
resp4 <- num1 / num2
escreval("|Resultado Divisão:", resp4)

Fimalgoritmo