Algoritmo "atividade_4"
// Disciplina  : Algoritmo e Lógica de Programação
// Professor   : André Olímpio 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Isabella Oliveira Assis
// Data atual  : 11/08/2026
Var

n1: inteiro

Inicio

escreva("|Digite um número:")
leia(n1)

SE (n1 > 0) ENTAO
   escreval("Número Positivo")
SENAO
     SE (n1 = 0) ENTAO
        escreval("Número Zero")
     SENAO
          escreval("Número Negativo")
     FIMSE
FIMSE

Fimalgoritmo