Algoritmo "atividade_14"
// Disciplina  : Algoritmo e Lógica de Programação
// Professor   : André Olímpio 
// Autor(a)    : Isabella
// Data atual  : 18/08/2026
Var
numero,resp: inteiro

Inicio
escreva("Digite um número inteiro:")
leia(numero)

escreval("|",numero,"x1=",numero)
resp <- numero * 2
escreval("|",numero,"x2=",resp)
resp <- numero * 3
escreval("|",numero,"x3=",resp)
resp <- numero * 4
escreval("|",numero,"x4=",resp)
resp <- numero * 5
escreval("|",numero,"x5=",resp)
resp <- numero * 6
escreval("|",numero,"x6=",resp)
resp <- numero * 7
escreval("|",numero,"x7=",resp)
resp <- numero * 8
escreval("|",numero,"x8=",resp)
resp <- numero * 9
escreval("|",numero,"x9=",resp)
resp <- numero * 10
escreval("|",numero,"x10=",resp)

Fimalgoritmo