Algoritmo "atividade_1"
// Disciplina  : Algoritmo e Lógica de Programação
// Professor   : André Olímpio 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Isabella Oliveira Assis
// Data atual  : 11/08/2026
Var

nome: caractere
idade: real
Inicio

escreva("|Digite seu nome:")
leia(nome)
escreva("|Digite sua idade:")
leia(idade)

escreva("Seja bem vindo ",nome)


Fimalgoritmo