Algoritmo "atividade_3"
// Disciplina  : Algoritmo e Lógica de Programação
// Professor   : André Olímpio 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Isabella Oliveira Assis
// Data atual  : 11/08/2026
Var
nota1, nota2, media: real
Inicio

Escreva("Digite a primeira nota: ")
Leia(nota1)

Escreva("Digite a segunda nota: ")
Leia(nota2)

media <- (nota1 + nota2) / 2

Escreva("A média do aluno é: ", media)

Fimalgoritmo