Algoritmo "atividade_6  "
// Disciplina  : Algoritmo e Lógica de Programação
// Professor   : André Olímpio 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Isabella Oliveira Assis
// Data atual  : 11/08/2026
Var
idade: inteiro

Inicio

escreva("Digite sua idade:")
leia(idade)

SE (idade >= 60) entao
   escreval("Pessoa idosa")
senao
     se (idade >=18) entao
        escreval("Pessoa Maior de Idade")
     senao
          ESCREVAL("Pessoa menor de idade")
     fimse
fimse
Fimalgoritmo